#ifndef DESUMANO_H_INCLUDED
#define DESUMANO_H_INCLUDED



#define TabelaPlayerAnim \
	X(VMM_PLAYER_ATAQUE,            4) \
	X(VMM_PLAYER_ATAQUE2,           6) \
	X(VMM_PLAYER_ATAQUE2_MOVIMENTO, 6) \
	X(VMM_PLAYER_ATAQUE_COMBO,      10) \
	X(VMM_PLAYER_ATAQUE_MOVIMENTO_COMBO, 10) \
	X(VMM_PLAYER_ATAQUE_MOVIMENTO, 4) \
	X(VMM_PLAYER_AGACHAR,          1) \
	X(VMM_PLAYER_AGACHAR_TODO,     3) \
	X(VMM_PLAYER_AGACHAR_ATAQUE,   4) \
	X(VMM_PLAYER_LEVANTAR,         1) \
	X(VMM_PLAYER_CORRER_AGACHADO,  8) \
	X(VMM_PLAYER_DASH,             2) \
	X(VMM_PLAYER_MORRER,          10) \
	X(VMM_PLAYER_MORRER_CORRENDO, 10) \
	X(VMM_PLAYER_CAIR,             3) \
	X(VMM_PLAYER_HIT,              1) \
	X(VMM_PLAYER_IDLE,            10) \
	X(VMM_PLAYER_PULAR,            3) \
	X(VMM_PLAYER_PULO_TRANSICAO,   2) \
	X(VMM_PLAYER_ROLAR,           12) \
	X(VMM_PLAYER_CORRER,          10) \
	X(VMM_PLAYER_DESLIZAR,         2)\
	X(VMM_PLAYER_DESLIZAR_TODO,    4) \
	X(VMM_PLAYER_DESLIZAR_TRANSICAO_FIM, 1) \
	X(VMM_PLAYER_DESLIZAR_TRANSICAO_COMECO, 1) \
	X(VMM_PLAYER_INVERTER_PASSO,   3) \
	X(VMM_PLAYER_ESCALAR,          7) \
	X(VMM_PLAYER_ESCALAR_MOVIMENTO,7) \
	X(VMM_PLAYER_AGARRAR,          1) \
	X(VMM_PLAYER_DESLIZAR_PAREDE,  3)

#define TabelaBlocoAtlas \
	/* GRAMA (0,0) a (4,4) - 5x5 = 25 tiles */ \
	X(VMM_BLOCO_GRAMA0x0, 0, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA0x1, 1, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA0x2, 2, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA0x3, 3, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA0x4, 4, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA1x0, 0, 1, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA1x1, 1, 1, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA1x2, 2, 1, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA1x3, 3, 1, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA1x4, 4, 1, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA2x0, 0, 2, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA2x1, 1, 2, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA2x2, 2, 2, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA2x3, 3, 2, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA2x4, 4, 2, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA3x0, 0, 3, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA3x1, 1, 3, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA3x2, 2, 3, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA3x3, 3, 3, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA3x4, 4, 3, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA4x0, 0, 4, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA4x1, 1, 4, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA4x2, 2, 4, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA4x3, 3, 4, VMMA_GRAMA_ON) \
	X(VMM_BLOCO_GRAMA4x4, 4, 4, VMMA_GRAMA_ON) \
	\
	/* PEDRA_GRAMA (0,10) a (1,11) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_PEDRA_GRAMA0x0, 0, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_GRAMA0x1, 1, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_GRAMA1x0, 0, 11, VMMA_PEDRA_ON) \
	X(VMM_BLOCO_PEDRA_GRAMA1x1, 1, 11, VMMA_PEDRA_ON) \
	\
	/* PEDRA_TRANSICAO (2,10) a (3,11) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_PEDRA_TRANSICAO0x0, 2, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_TRANSICAO0x1, 3, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_TRANSICAO1x0, 2, 11, VMMA_PEDRA_ON) \
	X(VMM_BLOCO_PEDRA_TRANSICAO1x1, 3, 11, VMMA_PEDRA_ON) \
	\
	/* FOLHA_CORPO (0,12) a (1,13) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_FOLHA_CORPO0x0, 0, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_CORPO0x1, 1, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_CORPO1x0, 0, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_CORPO1x1, 1, 13, VMMA_SEM_COLI) \
	\
	/* FOLHA_GALHO (2,12) a (3,13) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_FOLHA_GALHO0x0, 2, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_GALHO0x1, 3, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_GALHO1x0, 2, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_GALHO1x1, 3, 13, VMMA_SEM_COLI) \
	\
	/* FOLHA_TILES (0,14) a (2,16) - 3x3 = 9 tiles */ \
	X(VMM_BLOCO_FOLHA_TILES0x0, 0, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES0x1, 1, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES0x2, 2, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES1x0, 0, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES1x1, 1, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES1x2, 2, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES2x0, 0, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES2x1, 1, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FOLHA_TILES2x2, 2, 16, VMMA_SEM_COLI) \
	\
	/* AGUA_PEDRA (0,17) a (2,20) - 3x4 = 12 tiles */ \
	X(VMM_BLOCO_AGUA_PEDRA0x0, 0, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA0x1, 1, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA0x2, 2, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA1x0, 0, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA1x1, 1, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA1x2, 2, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2x0, 0, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2x1, 1, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2x2, 2, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA3x0, 0, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA3x1, 1, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA3x2, 2, 20, VMMA_SEM_COLI) \
	\
	/* AGUA_CACHOEIRA (3,17) a (5,20) - 3x4 = 12 tiles */ \
	X(VMM_BLOCO_AGUA_CACHOEIRA0x0, 3, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA0x1, 4, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA0x2, 5, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA1x0, 3, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA1x1, 4, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA1x2, 5, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA2x0, 3, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA2x1, 4, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA2x2, 5, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA3x0, 3, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA3x1, 4, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_CACHOEIRA3x2, 5, 20, VMMA_SEM_COLI) \
	\
	/* AGUA_PEDRA (6,18) a (9,20) - 4x3 = 12 tiles */ \
	X(VMM_BLOCO_AGUA_PEDRA2_0x0, 6, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_0x1, 7, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_0x2, 8, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_0x3, 9, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_1x0, 6, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_1x1, 7, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_1x2, 8, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_1x3, 9, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_2x0, 6, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_2x1, 7, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_2x2, 8, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_AGUA_PEDRA2_2x3, 9, 20, VMMA_SEM_COLI) \
	\
	/* MORRO_PEDRA (0,21) a (4,22) - 5x2 = 10 tiles */ \
	X(VMM_BLOCO_MORRO_PEDRA0x0, 0, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA0x1, 1, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA0x2, 2, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA0x3, 3, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA0x4, 4, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA1x0, 0, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA1x1, 1, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA1x2, 2, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA1x3, 3, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA1x4, 4, 22, VMMA_SEM_COLI) \
	\
	/* MORRO_PEDRA_P (5,21) a (9,22) - 5x2 = 10 tiles */ \
	X(VMM_BLOCO_MORRO_PEDRA_P0x0, 5, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P0x1, 6, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P0x2, 7, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P0x3, 8, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P0x4, 9, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P1x0, 5, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P1x1, 6, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P1x2, 7, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P1x3, 8, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_P1x4, 9, 22, VMMA_SEM_COLI) \
	\
	/* MORRO_PEDRA_PP (10,21) a (14,22) - 5x2 = 10 tiles */ \
	X(VMM_BLOCO_MORRO_PEDRA_PP0x0, 10, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP0x1, 11, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP0x2, 12, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP0x3, 13, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP0x4, 14, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP1x0, 10, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP1x1, 11, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP1x2, 12, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP1x3, 13, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_PEDRA_PP1x4, 14, 22, VMMA_SEM_COLI) \
	\
	/* PEDRA_MARRON_CORPO (4,10) a (5,11) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_PEDRA_MARRON_CORPO0x0, 4, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_CORPO0x1, 5, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_CORPO1x0, 4, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_CORPO1x1, 5, 11, VMMA_SEM_COLI) \
	\
	/* PEDRA_MARRON_TILES (6,10) a (8,12) - 3x3 = 9 tiles */ \
	X(VMM_BLOCO_PEDRA_MARRON_TILES0x0, 6, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES0x1, 7, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES0x2, 8, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES1x0, 6, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES1x1, 7, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES1x2, 8, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES2x0, 6, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES2x1, 7, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_TILES2x2, 8, 12, VMMA_SEM_COLI) \
	\
	/* PEDRA_MARRON_DEGRI (9,10) a (9,12) - 1x3 = 3 tiles */ \
	X(VMM_BLOCO_PEDRA_MARRON_DEGRI0x0, 9, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_DEGRI1x0, 9, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_MARRON_DEGRI2x0, 9, 12, VMMA_SEM_COLI) \
	\
	/* ARVORE_GALHO (4,13) a (8,16) - 5x4 = 20 tiles */ \
	X(VMM_BLOCO_ARVORE_GALHO0x0, 4, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO0x1, 5, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO0x2, 6, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO0x3, 7, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO0x4, 8, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO1x0, 4, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO1x1, 5, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO1x2, 6, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO1x3, 7, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO1x4, 8, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO2x0, 4, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO2x1, 5, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO2x2, 6, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO2x3, 7, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO2x4, 8, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO3x0, 4, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO3x1, 5, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO3x2, 6, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO3x3, 7, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_GALHO3x4, 8, 16, VMMA_SEM_COLI) \
	\
	/* PILASTRA_HORIZONTAL (10,14) a (10,16) - 1x3 = 3 tiles */ \
	X(VMM_BLOCO_PILASTRA_HORIZONTAL0x0, 10, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_HORIZONTAL1x0, 10, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_HORIZONTAL2x0, 10, 16, VMMA_SEM_COLI) \
	\
	/* PILASTRA_VERTICAL (11,14) a (13,15) - 3x2 = 6 tiles */ \
	X(VMM_BLOCO_PILASTRA_VERTICAL0x0, 11, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_VERTICAL0x1, 12, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_VERTICAL0x2, 13, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_VERTICAL1x0, 11, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_VERTICAL1x1, 12, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PILASTRA_VERTICAL1x2, 13, 15, VMMA_SEM_COLI) \
	\
	/* TIJOLO_PEDRA (10,12) a (12,13) - 3x2 = 6 tiles */ \
	X(VMM_BLOCO_TIJOLO_PEDRA0x0, 10, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_TIJOLO_PEDRA0x1, 11, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_TIJOLO_PEDRA0x2, 12, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_TIJOLO_PEDRA1x0, 10, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_TIJOLO_PEDRA1x1, 11, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_TIJOLO_PEDRA1x2, 12, 13, VMMA_SEM_COLI) \
	\
	/* GALHO_SOLO (10,10) a (14,11) - 5x2 = 10 tiles */ \
	X(VMM_BLOCO_GALHO_SOLO0x0, 10, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO0x1, 11, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO0x2, 12, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO0x3, 13, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO0x4, 14, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO1x0, 10, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO1x1, 11, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO1x2, 12, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO1x3, 13, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GALHO_SOLO1x4, 14, 11, VMMA_SEM_COLI) \
	\
	/* PONTE (5,7) a (9,9) - 5x3 = 15 tiles */ \
	X(VMM_BLOCO_PONTE0x0, 5, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE0x1, 6, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE0x2, 7, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE0x3, 8, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE0x4, 9, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE1x0, 5, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE1x1, 6, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE1x2, 7, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE1x3, 8, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE1x4, 9, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE2x0, 5, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE2x1, 6, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE2x2, 7, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE2x3, 8, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PONTE2x4, 9, 9, VMMA_SEM_COLI) \
	\
	/* PISO (5,5) a (7,6) - 3x2 = 6 tiles */ \
	X(VMM_BLOCO_PISO0x0, 5, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PISO0x1, 6, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PISO0x2, 7, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PISO1x0, 5, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PISO1x1, 6, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PISO1x2, 7, 6, VMMA_SEM_COLI) \
	\
	/* MORRO_GRAMA (5,0) a (6,3) - 2x4 = 8 tiles */ \
	X(VMM_BLOCO_MORRO_GRAMA0x0, 5, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA0x1, 6, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA1x0, 5, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA1x1, 6, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA2x0, 5, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA2x1, 6, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA3x0, 5, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MORRO_GRAMA3x1, 6, 3, VMMA_SEM_COLI) \
	\
	/* GRAMA_PEDRA (5,4) a (6,4) - 2x1 = 2 tiles */ \
	X(VMM_BLOCO_GRAMA_PEDRA0x0, 5, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_GRAMA_PEDRA0x1, 6, 4, VMMA_SEM_COLI) \
	\
	/* PEDRA_GRAMA (7,3) a (7,4) - 1x2 = 2 tiles */ \
	X(VMM_BLOCO_PEDRA_GRAMA2_0x0, 7, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_GRAMA2_1x0, 7, 4, VMMA_SEM_COLI) \
	\
	/* PEDRA_BAIXA (7,0) a (8,2) - 2x3 = 6 tiles */ \
	X(VMM_BLOCO_PEDRA_BAIXA0x0, 7, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_BAIXA0x1, 8, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_BAIXA1x0, 7, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_BAIXA1x1, 8, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_BAIXA2x0, 7, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_PEDRA_BAIXA2x1, 8, 2, VMMA_SEM_COLI) \
	\
	/* ARVORE_CIMA (9,0) a (12,13) - 4x14 = 56 tiles */ \
	X(VMM_BLOCO_ARVORE_CIMA0x0, 9, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA0x1, 10, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA0x2, 11, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA0x3, 12, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA1x0, 9, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA1x1, 10, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA1x2, 11, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA1x3, 12, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA2x0, 9, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA2x1, 10, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA2x2, 11, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA2x3, 12, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA3x0, 9, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA3x1, 10, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA3x2, 11, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA3x3, 12, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA4x0, 9, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA4x1, 10, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA4x2, 11, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA4x3, 12, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA5x0, 9, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA5x1, 10, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA5x2, 11, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA5x3, 12, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA6x0, 9, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA6x1, 10, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA6x2, 11, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA6x3, 12, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA7x0, 9, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA7x1, 10, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA7x2, 11, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA7x3, 12, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA8x0, 9, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA8x1, 10, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA8x2, 11, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA8x3, 12, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA9x0, 9, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA9x1, 10, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA9x2, 11, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA9x3, 12, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA10x0, 9, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA10x1, 10, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA10x2, 11, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA10x3, 12, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA11x0, 9, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA11x1, 10, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA11x2, 11, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA11x3, 12, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA12x0, 9, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA12x1, 10, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA12x2, 11, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA12x3, 12, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA13x0, 9, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA13x1, 10, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA13x2, 11, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_CIMA13x3, 12, 13, VMMA_SEM_COLI) \
	\
	/* ARVORE_BURACO (8,4) a (9,5) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_ARVORE_BURACO0x0, 8, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BURACO0x1, 9, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BURACO1x0, 8, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BURACO1x1, 9, 5, VMMA_SEM_COLI) \
	\
	/* ARVORE_BAIXO (10,4) a (13,9) - 4x6 = 24 tiles */ \
	X(VMM_BLOCO_ARVORE_BAIXO0x0, 10, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO0x1, 11, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO0x2, 12, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO0x3, 13, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO1x0, 10, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO1x1, 11, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO1x2, 12, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO1x3, 13, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO2x0, 10, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO2x1, 11, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO2x2, 12, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO2x3, 13, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO3x0, 10, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO3x1, 11, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO3x2, 12, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO3x3, 13, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO4x0, 10, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO4x1, 11, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO4x2, 12, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO4x3, 13, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO5x0, 10, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO5x1, 11, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO5x2, 12, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_BAIXO5x3, 13, 9, VMMA_SEM_COLI) \
	\
	/* ARVORE_ESCURA (13,0) a (14,13) - 2x14 = 28 tiles */ \
	X(VMM_BLOCO_ARVORE_ESCURA0x0, 13, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA0x1, 14, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA1x0, 13, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA1x1, 14, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA2x0, 13, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA2x1, 14, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA3x0, 13, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA3x1, 14, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA4x0, 13, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA4x1, 14, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA5x0, 13, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA5x1, 14, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA6x0, 13, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA6x1, 14, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA7x0, 13, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA7x1, 14, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA8x0, 13, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA8x1, 14, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA9x0, 13, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA9x1, 14, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA10x0, 13, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA10x1, 14, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA11x0, 13, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA11x1, 14, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA12x0, 13, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA12x1, 14, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA13x0, 13, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARVORE_ESCURA13x1, 14, 13, VMMA_SEM_COLI) \
	\
	/* ARBUSTOP (17,0) a (24,2) - 8x3 = 24 tiles */ \
	X(VMM_BLOCO_ARBUSTOP0x0, 17, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x1, 18, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x2, 19, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x3, 20, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x4, 21, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x5, 22, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x6, 23, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP0x7, 24, 0, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x0, 17, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x1, 18, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x2, 19, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x3, 20, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x4, 21, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x5, 22, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x6, 23, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP1x7, 24, 1, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x0, 17, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x1, 18, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x2, 19, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x3, 20, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x4, 21, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x5, 22, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x6, 23, 2, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOP2x7, 24, 2, VMMA_SEM_COLI) \
	\
	/* ARBUSTOPP (17,3) a (24,5) - 8x3 = 24 tiles */ \
	X(VMM_BLOCO_ARBUSTOPP0x0, 17, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x1, 18, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x2, 19, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x3, 20, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x4, 21, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x5, 22, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x6, 23, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP0x7, 24, 3, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x0, 17, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x1, 18, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x2, 19, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x3, 20, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x4, 21, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x5, 22, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x6, 23, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP1x7, 24, 4, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x0, 17, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x1, 18, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x2, 19, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x3, 20, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x4, 21, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x5, 22, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x6, 23, 5, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPP2x7, 24, 5, VMMA_SEM_COLI) \
	\
	/* ARBUSTOPPP (17,6) a (24,8) - 8x3 = 24 tiles */ \
	X(VMM_BLOCO_ARBUSTOPPP0x0, 17, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x1, 18, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x2, 19, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x3, 20, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x4, 21, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x5, 22, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x6, 23, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP0x7, 24, 6, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x0, 17, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x1, 18, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x2, 19, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x3, 20, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x4, 21, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x5, 22, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x6, 23, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP1x7, 24, 7, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x0, 17, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x1, 18, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x2, 19, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x3, 20, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x4, 21, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x5, 22, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x6, 23, 8, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPP2x7, 24, 8, VMMA_SEM_COLI) \
	\
	/* ARBUSTOPPPP (17,9) a (24,11) - 8x3 = 24 tiles */ \
	X(VMM_BLOCO_ARBUSTOPPPP0x0, 17, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x1, 18, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x2, 19, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x3, 20, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x4, 21, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x5, 22, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x6, 23, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP0x7, 24, 9, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x0, 17, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x1, 18, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x2, 19, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x3, 20, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x4, 21, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x5, 22, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x6, 23, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP1x7, 24, 10, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x0, 17, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x1, 18, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x2, 19, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x3, 20, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x4, 21, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x5, 22, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x6, 23, 11, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPP2x7, 24, 11, VMMA_SEM_COLI) \
	\
	/* ARBUSTOPPPPP (17,12) a (24,14) - 8x3 = 24 tiles */ \
	X(VMM_BLOCO_ARBUSTOPPPPP0x0, 17, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x1, 18, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x2, 19, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x3, 20, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x4, 21, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x5, 22, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x6, 23, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP0x7, 24, 12, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x0, 17, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x1, 18, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x2, 19, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x3, 20, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x4, 21, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x5, 22, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x6, 23, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP1x7, 24, 13, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x0, 17, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x1, 18, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x2, 19, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x3, 20, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x4, 21, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x5, 22, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x6, 23, 14, VMMA_SEM_COLI) \
	X(VMM_BLOCO_ARBUSTOPPPPP2x7, 24, 14, VMMA_SEM_COLI) \
	\
	/* COGUMELO (15,15) a (22,16) - 8x2 = 16 tiles */ \
	X(VMM_BLOCO_COGUMELO0x0, 15, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x1, 16, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x2, 17, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x3, 18, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x4, 19, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x5, 20, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x6, 21, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO0x7, 22, 15, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x0, 15, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x1, 16, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x2, 17, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x3, 18, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x4, 19, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x5, 20, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x6, 21, 16, VMMA_SEM_COLI) \
	X(VMM_BLOCO_COGUMELO1x7, 22, 16, VMMA_SEM_COLI) \
	\
	/* FRASCO (15,22) a (19,24) - 5x3 = 15 tiles */ \
	X(VMM_BLOCO_FRASCO0x0, 15, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO0x1, 16, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO0x2, 17, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO0x3, 18, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO0x4, 19, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO1x0, 15, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO1x1, 16, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO1x2, 17, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO1x3, 18, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO1x4, 19, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO2x0, 15, 24, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO2x1, 16, 24, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO2x2, 17, 24, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO2x3, 18, 24, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FRASCO2x4, 19, 24, VMMA_SEM_COLI) \
	\
	/* MATO (20,22) a (21,23) - 2x2 = 4 tiles */ \
	X(VMM_BLOCO_MATO0x0, 20, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MATO0x1, 21, 22, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MATO1x0, 20, 23, VMMA_SEM_COLI) \
	X(VMM_BLOCO_MATO1x1, 21, 23, VMMA_SEM_COLI) \
	\
	/* JARRO (21,19) a (24,20) - 4x2 = 8 tiles */ \
	X(VMM_BLOCO_JARRO0x0, 21, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO0x1, 22, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO0x2, 23, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO0x3, 24, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO1x0, 21, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO1x1, 22, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO1x2, 23, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_JARRO1x3, 24, 20, VMMA_SEM_COLI) \
	\
	/* BAU (18,17) a (21,18) - 4x2 = 8 tiles */ \
	X(VMM_BLOCO_BAU0x0, 18, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU0x1, 19, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU0x2, 20, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU0x3, 21, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU1x0, 18, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU1x1, 19, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU1x2, 20, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_BAU1x3, 21, 18, VMMA_SEM_COLI) \
	\
	/* FLOR (15,17) a (15,18) - 1x2 = 2 tiles */ \
	X(VMM_BLOCO_FLOR0x0, 15, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_FLOR1x0, 15, 18, VMMA_SEM_COLI) \
	\
	/* FLORP (16,17) - 1x1 = 1 tile */ \
	X(VMM_BLOCO_FLORP0x0, 16, 17, VMMA_SEM_COLI) \
	\
	/* DENTE_LEAO (16,18) a (16,19) - 1x2 = 2 tiles */ \
	X(VMM_BLOCO_DENTE_LEAO0x0, 16, 18, VMMA_SEM_COLI) \
	X(VMM_BLOCO_DENTE_LEAO1x0, 16, 19, VMMA_SEM_COLI) \
	\
	/* DENTE_LEAOP (16,20) a (16,21) - 1x2 = 2 tiles */ \
	X(VMM_BLOCO_DENTE_LEAOP0x0, 16, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_DENTE_LEAOP1x0, 16, 21, VMMA_SEM_COLI) \
	\
	/* TOCHA (15,19) - 1x1 = 1 tile */ \
	X(VMM_BLOCO_TOCHA0x0, 15, 19, VMMA_SEM_COLI) \
	\
	/* CHAVE (15,19) - 1x1 = 1 tile */ \
	X(VMM_BLOCO_CHAVE0x0, 15, 19, VMMA_SEM_COLI) \
	\
	/* MOEDA (15,19) - 1x1 = 1 tile */ \
	X(VMM_BLOCO_MOEDA0x0, 15, 19, VMMA_SEM_COLI) \
	\
	/* VITORIA (17,19) a (20,21) - 4x3 = 12 tiles */ \
	X(VMM_BLOCO_VITORIA0x0, 17, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA0x1, 18, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA0x2, 19, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA0x3, 20, 19, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA1x0, 17, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA1x1, 18, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA1x2, 19, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA1x3, 20, 20, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA2x0, 17, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA2x1, 18, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA2x2, 19, 21, VMMA_SEM_COLI) \
	X(VMM_BLOCO_VITORIA2x3, 20, 21, VMMA_SEM_COLI) \
	\
	/* CORAL (17,17) a (17,18) - 1x2 = 2 tiles */ \
	X(VMM_BLOCO_CORAL0x0, 17, 17, VMMA_SEM_COLI) \
	X(VMM_BLOCO_CORAL1x0, 17, 18, VMMA_SEM_COLI) \
	\
	/* COISA (22,17) - 1x1 = 1 tile */ \
	X(VMM_BLOCO_COISA0x0, 22, 17, VMMA_SEM_COLI)

#define TabelaPorcoAnim \
	X(VMM_PORCO_ANDAR,   6) \
	X(VMM_PORCO_CORRER,  6) \
	X(VMM_PORCO_IDLE,    4) \
	X(VMM_PORCO_HIT,     4) \

typedef enum{
	PORCO_NORMAL,
	ABELHA,
	CARACOL,
} TiposInimigo;

typedef enum {
	VMMA_SEM_COLI,
	VMMA_GRAMA_ON,
	VMMA_PEDRA_ON,
} TiposVMMA;





#define X(index, quant) index,
typedef enum {
				 TabelaPlayerAnim
} ESTADO_PLAYER;

typedef enum {
				 TabelaPorcoAnim
} ESTADO_PORCO;

#undef X

#define X(index, x_loc, y_loc, tipo) index,

typedef enum {
								TabelaBlocoAtlas
} IndexImgBloco;

#undef X



#endif // DESUMANO_H_INCLUDED
